name: Deploy to GAE
on:
  push:
    branches:
      - master
      - release/*
  release:
    types:
      - prereleased
      - released

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: setup-nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.1
          registry-url: https://npm.pkg.github.com/
          scope: '@OWNER'

      - uses: ./.github/actions/deploy-gae
        name: Deploy to GAE
        env:
          dev_service_account: ${{ secrets.DEV_GCP_SERVICE_ACCOUNT }}
          qa1_service_account: ${{ secrets.QA1_GCP_SERVICE_ACCOUNT }}
          preprod_service_account: ${{ secrets.PREPROD_GCP_SERVICE_ACCOUNT }}
          prod_service_account: ${{ secrets.PROD_GCP_SERVICE_ACCOUNT }}
